# Generated by Django 4.2.11 on 2024-04-18 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='updaetd_at',
            new_name='updated_at',
        ),
    ]
