# Generated by Django 4.2.11 on 2024-04-18 05:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_rename_post_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='check_users',
            field=models.ManyToManyField(related_name='check_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
